# Generated by Django 4.2.7 on 2025-09-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='targets',
            field=models.TextField(blank=True, help_text='Comma-separated list of target domains, IPs, or URLs for this organization', null=True),
        ),
    ]
