# Generated by Django 4.2.7 on 2025-09-28 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_add_targets_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Organization name can only contain letters, numbers, spaces, hyphens, and underscores.', regex='^[a-zA-Z0-9\\s\\-_]+$')]),
        ),
    ]
