# Generated by Django 4.2.7 on 2025-09-23 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('exploit_script', 'Exploit Script'), ('report', 'Report'), ('screenshot', 'Screenshot'), ('log_file', 'Log File'), ('config_file', 'Configuration File'), ('custom', 'Custom')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('s3_key', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scan_artifacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(choices=[('reconnaissance', 'Reconnaissance'), ('vulnerability', 'Vulnerability'), ('exploitation', 'Exploitation'), ('post_exploitation', 'Post-Exploitation'), ('custom', 'Custom')], max_length=30)),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_version', models.CharField(blank=True, max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('severity', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_output_s3_key', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'scan_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('uploaded', 'Archive Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('archive_s3_key', models.CharField(max_length=500)),
                ('archive_size', models.BigIntegerField()),
                ('archive_checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_log', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_scans', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to='organizations.organization')),
            ],
            options={
                'db_table': 'scan_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('domain', 'Domain'), ('ip', 'IP Address'), ('url', 'URL'), ('subdomain', 'Subdomain'), ('email', 'Email Address'), ('port', 'Port'), ('service', 'Service'), ('file', 'File Path'), ('endpoint', 'API Endpoint')], max_length=20)),
                ('value', models.CharField(max_length=500)),
                ('discovered_by', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_alive', models.BooleanField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_targets', to='reports.target')),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='reports.scansession')),
            ],
            options={
                'db_table': 'targets',
            },
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='report',
        ),
        migrations.DeleteModel(
            name='PentestReport',
        ),
        migrations.DeleteModel(
            name='Vulnerability',
        ),
        migrations.AddField(
            model_name='scanresult',
            name='scan_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='reports.scansession'),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='reports.target'),
        ),
        migrations.AddField(
            model_name='scanartifact',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='reports.scanresult'),
        ),
        migrations.AddField(
            model_name='scanartifact',
            name='scan_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='reports.scansession'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['scan_session', 'target_type'], name='targets_scan_se_16b963_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['scan_session', 'is_primary'], name='targets_scan_se_85a9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['parent_target'], name='targets_parent__1d50ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='target',
            unique_together={('scan_session', 'value')},
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['scan_session', 'result_type'], name='scan_result_scan_se_3cf7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['scan_session', 'tool_name'], name='scan_result_scan_se_3008d2_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['scan_session', 'severity'], name='scan_result_scan_se_168a99_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['target', 'result_type'], name='scan_result_target__0b6ea0_idx'),
        ),
    ]
