# Generated by Django 4.2.7 on 2025-09-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_scanartifact_scanresult_scansession_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansession',
            name='archive_file',
            field=models.FileField(blank=True, help_text='ZIP file containing scan results', null=True, upload_to='scans/archives/'),
        ),
        migrations.AlterField(
            model_name='scansession',
            name='archive_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='scansession',
            name='archive_s3_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='scansession',
            name='archive_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
