# Generated by Django 4.2.7 on 2025-09-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_scansession_archive_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scansession',
            name='archive_file',
            field=models.FileField(default='', help_text='ZIP file containing scan results', upload_to='scans/archives/'),
        ),
    ]
