# Generated by Django 4.2.7 on 2025-09-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_scansession_archive_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scansession',
            name='name',
        ),
    ]
