# Generated by Django 4.2.7 on 2025-09-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_scansession_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanartifact',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='scansession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
