# Generated by Django 4.2.7 on 2025-09-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_scanartifact_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scansession',
            name='archive_checksum',
        ),
        migrations.RemoveField(
            model_name='scansession',
            name='archive_s3_key',
        ),
        migrations.RemoveField(
            model_name='scansession',
            name='archive_size',
        ),
    ]
