# Generated by Django 4.2.7 on 2025-10-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_scanresult_result_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanresult',
            options={'ordering': ['severity', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['severity', '-created_at'], name='scan_result_severit_ada0a9_idx'),
        ),
    ]
