# Generated by Django 4.2.7 on 2025-10-09 12:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_add_severity_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResultAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('exploit_script', 'Exploit Script'), ('extracted_data', 'Extracted Data'), ('screenshot', 'Screenshot'), ('log_file', 'Log File'), ('raw_output', 'Raw Output'), ('config_file', 'Configuration File'), ('payload', 'Payload'), ('evidence', 'Evidence'), ('other', 'Other')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('original_path', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('s3_key', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scan_result_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='scanresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='scanresult',
            name='scan_result_severit_ada0a9_idx',
        ),
        migrations.AddField(
            model_name='scanresultattachment',
            name='scan_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.scanresult'),
        ),
        migrations.AddIndex(
            model_name='scanresultattachment',
            index=models.Index(fields=['scan_result', 'attachment_type'], name='scan_result_scan_re_1e9dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresultattachment',
            index=models.Index(fields=['attachment_type'], name='scan_result_attachm_5d5719_idx'),
        ),
    ]
